#!/usr/bin/env bash
#
# Pre-push hook that runs tests for python 2 and 3
#
# git config core.hooksPath .githooks should be run before this
#

if [[ -n $VIRTUAL_ENV ]]; then
    echo 'Running inside a virtual env. Deactivating.'
    source "$VIRTUAL_ENV"/bin/activate
    deactivate
fi

python2path="/Users/virgil/.local/share/virtualenvs/NukeServerSocket-QnyVgKFM/bin/python"
if [[ -z $python2path ]]; then
    
    if [[ ! -d .venv ]]; then
        echo "root/.venv/bin/python not found."
        echo "Set python2path inside .githooks/pre-push or create virtual env inside root:"
        echo "python2 -m virtualenv .venv"
        exit 1
    fi

    echo "python2path is not specified. fallback on root/.venv/bin/python"
    python2path=.venv/bin/python
fi


if ! $python2path -m pytest; then
    echo "Python 2 tests failed"
fi

python3path="poetry"
if ! $python3path run pytest --cov=src --cov-report=html:coverage --cov-report=xml; then
    echo "Python 3 tests failed"
    exit 1
fi

# TODO: add coverage report
# TODO: check pyproject version match with current version